# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- del

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.14.10'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environment/test'
    backendType: 'azurerm'
    backendServiceArm: '従量課金(121a3543-1cf4-4852-8b13-d230af5db949)'
    backendAzureRmResourceGroupName: 'tstate'
    backendAzureRmStorageAccountName: 'tstate210319'
    backendAzureRmContainerName: 'azuredevproject1'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: true


#- task: Bash@3
#  inputs:
#    targetType: 'inline'
#    script: 'terraform    force-unlock -force  ce2637f8-1d35-6780-2579-f73c08aca52f  ' 
#    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environment/test'

- task: TerraformCLI@0
  inputs:
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environment/test'
    environmentServiceName: '従量課金(121a3543-1cf4-4852-8b13-d230af5db949)'
    allowTelemetryCollection: true
